[package]
name = "rust-token-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
env_logger = "0.11.5"
indicatif = "0.17.8"
log = "0.4.22"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
sha2 = "0.10.8"
